### PR TITLE
Fail installation when .NET processes are detected, but none are found in systemd

### PR DESCRIPTION
**Pull request by JcolemanNR**
If the user is running .net processes outside of systemd then the install will complete on Linux, but no services will have been instrumented.

To improve the user experience, we would like to detect this scenario and fail the install.

Resolves: https://github.com/newrelic/newrelic-dotnet-agent/issues/662

### CODE REVIEW

**Comment by JcolemanNR** [comment]
Not sure why the GHA tests are failing... Is this related to my changes to the .net agent linux-systemd recipe? 

I attempted manually running the action, but it appears to skip the failing steps when manually triggered

**Comment by Julien4218** [comment]
> Not sure why the GHA tests are failing... Is this related to my changes to the .net agent linux-systemd recipe?
> 
> I attempted manually running the action, but it appears to skip the failing steps when manually triggered

So this is a known issue of the PR job, could you get the latest main into your branch, that should fix the failing tests.

**Review by Julien4218 — APPROVED** [review]

**Comment by Julien4218** [comment]
@JcolemanNR I've fixed the incorrect test failure issue, the PR is now good to go.
@jaffinito are you ok/good getting this work out?

**Review by jaffinito — APPROVED** [review]
This looks good to me!

**Comment by Julien4218** [comment]
This was deployed to production us/eu with the newrelic-cli 0.32.1 release https://github.com/newrelic/newrelic-cli/releases/tag/v0.32.1

**Pull request merged**
