### PR TITLE
Adds jq error code

### PR DESCRIPTION
**Pull request by jaffinito**
jq is going to be used in the .NET Agent install recipe for Linux

### CODE REVIEW

**Comment by gabeobrien** [comment]
For the Java recipe I pulled JQ out and replaced it with 'sed'.  Not ideal but we opted to not deal with installing packages on the customer machine if we can help it.

**Comment by Julien4218** [comment]
> For the Java recipe I pulled JQ out and replaced it with 'sed'. Not ideal but we opted to not deal with installing packages on the customer machine if we can help it.

Yeah if we can workaround with `sed` that would be a lot better than installing jq, we already have a pre check assertion that makes sure sed is installed, which it is usually

**Comment by gabeobrien** [comment]
Here are the two ways that I pull data out of the JSON output from the Java CLI:
https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/java/rhel.yml#L60
https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/java/rhel.yml#L64
Happy to help with this as needed.

**Comment by jaffinito** [comment]
Alex found a way to break things up in our current PR.  Going to close this out since we appear to be able to drop jq.

**Pull request closed without merging**
