### PR TITLE
Detect unsupported windows version and re-route the user to manual install

### PR DESCRIPTION
**Pull request by Julien4218**
https://newrelic.atlassian.net/browse/VIRTUOSO-959

### CODE REVIEW

**Comment by Julien4218** [comment]
Testing on a windows 2012 R2 server by running the recipe using Github URL (no service call to match with target host though).

[windows2012r2.txt](https://github.com/newrelic/open-install-library/files/6542720/windows2012r2.txt)

**Comment by Julien4218** [comment]
@jaffinito I took a stab at implementing the recipe to specifically handle the Windows 2012 server.
I've fetched the specific value to look for from our event data. I also noticed we should cover 2012 R2 and 2012 as well.
Let me know your feedback.
We can do another round of testing with the service and target matching on staging once it's merged.

**Review by jaffinito — DISMISSED** [review]
Versions match up to the 2012 family.
I do have one comment, "Installation of the .NET Agent is not available for this version of windows" reads like this version of Windows is not support at all for the .NET Agent, despite there being a link to more options.  Maybe "Installation of the .NET Agent is not available for this version of windows using this procedure"?

**Comment by angelatan2** [comment]
This is probably a little late.  On the comment above stated by Jacob - I think an active voice is better.  "Please use standard install method for Window 2012 R2 version".  Point them to the link to get them there.

**Comment by Julien4218** [comment]
> Versions match up to the 2012 family.
> I do have one comment, "Installation of the .NET Agent is not available for this version of windows" reads like this version of Windows is not support at all for the .NET Agent, despite there being a link to more options. Maybe "Installation of the .NET Agent is not available for this version of windows using this procedure"?

Good catch. I've updated the message. Thanks @jaffinito

**Comment by jaffinito** [comment]
@angelatan2 I really like that wording!  Thoughts @Julien4218 ?

**Comment by Julien4218** [comment]
> This is probably a little late. On the comment above stated by Jacob - I think an active voice is better. "Please use standard install method for Window 2012 R2 version". Point them to the link to get them there.

Yes @angelatan2 we are giving them the URL to follow for continuing the installation. The full message would look like this:

Installation of the .NET Agent is not available for this version of windows using this tool
Please see our other installation options:
https://docs.newrelic.com/docs/agents/net-agent/installation/install-net-agent-windows/.

**Pull request merged**
