### PR TITLE
Disable logging for unsupported ubuntu versions

### PR DESCRIPTION
**Pull request by Julien4218**

### CODE REVIEW

**Review by jbeveland27 — COMMENTED** [review]
Nice catch @Julien4218. Is it worth adding an ubuntu 14 test definition to run infra install + this `ubuntu-unsupported` recipe together?

**Comment by Julien4218** [comment]
> Nice catch @Julien4218. Is it worth adding an ubuntu 14 test definition to run infra install + this `ubuntu-unsupported` recipe together?

Yeah, we already have a test definition for ubuntu 14, and it does pull the log recipe too since we install as guided install now for the infra tests.

**Review by zlesnr — DISMISSED** [review]

**Comment by jbeveland27** [comment]
Ah right, I forgot we switched that to guided install

**Review by jbeveland27 — APPROVED** [review]

**Comment by Julien4218** [comment]
Related and dependent PR on the library service to be deployed before this change 
https://source.datanerd.us/open-source/open-install-library-service/pull/34

**Comment by Julien4218** [comment]
@jbeveland27 I've started to test the service change on staging, and notice the centos/rhel recipes needed their platformVersion to be removed otherwise those recipes would now get filtered out by the service.
So I've removed those.

I have the service deployed on Staging, and at this point I feel confident merging this PR and deployed it to Staging to finish the manual non-regression testing and the ubuntu 14 log testing as well.

Let me know if you have any objections

**Pull request merged**
