### PR TITLE
feat: add postInstall to recipes

### PR DESCRIPTION
**Pull request by jbeveland27**

### CODE REVIEW

**Comment by jbeveland27** [comment]
Here's a sample running Infra-Agent, Logs, and MySQL on Linux2 host:

```
Starting installation.
Installing New Relic CLI v0.18.30
Installing to /usr/local/bin using sudo

   _   _                 ____      _ _
  | \ | | _____      __ |  _ \ ___| (_) ___
  |  \| |/ _ \ \ /\ / / | |_) / _ | | |/ __|
  | |\  |  __/\ V  V /  |  _ |  __| | | (__
  |_| \_|\___| \_/\_/   |_| \_\___|_|_|\___|

  Welcome to New Relic. Let's install some instrumentation.

  Questions? Read more about our installation process at
  https://docs.newrelic.com/


The following will be installed:
  Infrastructure Agent
  Logs integration
  MySQL Open Source Integration

==> Installing infrastructure-agent-installer...
Package newrelic-infra-1.15.2-1.el7.x86_64 already installed and latest version
    ✅ Checking for data in New Relic...success.
  ⚙️  The Infrastructure Agent configuration file can be found in /etc/newrelic-infra.yml
  Edit this file to make changes or configure advanced features for the agent. See the docs for options:
  https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings

==> Installing infrastructure-agent-installer...success.

==> Installing logs-integration...
  - Which log files would you like to tail? /var/log/messages,/var/log/cloud-init.log,/var/log/secure
    ✅ Checking for data in New Relic...success.
  ⚙️  The Logs configuration file (base configuration) can be found in /etc/newrelic-infra/logging.d/logging.yml
  ⚙️  The Logs configuration file for discovered processes can be found in /etc/newrelic-infra/logging.d/discovered.yml
  Edit these files to make changes or configure advanced features for the Logs integration. See the docs for options:
  https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters

==> Installing logs-integration...success.

==> Installing mysql-open-source-integration...
  To capture data from the MySQL integration, you'll first need to meet these prerequisites:
  - MySQL version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#req)
  - User with replication permissions

  To create a new user, use these commands as reference (Note: username,
  password, and similar user-specific values must be replaced):

  > sudo mysql -e "CREATE USER 'newrelic'@'localhost' IDENTIFIED BY 'YOUR_SELECTED_PASSWORD';"
  > sudo mysql -e "GRANT REPLICATION CLIENT ON *.* TO 'newrelic'@'localhost' WITH MAX_USER_CONNECTIONS 5;"
  > sudo mysql -e "GRANT SELECT ON *.* TO 'newrelic'@'localhost' WITH MAX_USER_CONNECTIONS 5;"

  - MySQL Username newrelic
MySQL Hostname (default: localhost) █ocalhost
MySQL port (default: 3306) █306
  - MySQL Database Name MysqlSample
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
268 packages excluded due to repository priority protections
Package nri-mysql-1.4.0-1.x86_64 already installed and latest version
Nothing to do
    ✅ Checking for data in New Relic...success.
  ⚙️  The MySQL configuration file can be found in /etc/newrelic-infra/integrations.d/mysql-config.yml
  Edit this file to make changes or configure advanced features for this integration. See the docs for options:
  https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration#config

==> Installing mysql-open-source-integration...success.

  New Relic installation complete!
  ```

**Comment by jbeveland27** [comment]
@Julien4218 having your eyes on the Windows changes would be very helpful. I'm a bit confused on how we're using `windows-logs.yml`, as there's also an inclusion of Logs in the windows infra-agent recipe. So some confirmation of what's there would be helpful.

**Review by Julien4218 — COMMENTED** [review]
@jbeveland27 just reading through the changes.
I'm not quite following the syntax of |2 and the gear icon, I assume you've validated it displays correctly on linux and windows?
One thing to do maybe, it would be nice to keep all the go-task related schema together,  and therefore to move the postInstall higher in the file with all the other fields we've added

**Comment by jbeveland27** [comment]
@Julien4218 The `|2` is a yaml syntax: it allows for literal text and also adds 2 spaces before the text. It basically lines all the text up as expected. The gear icon was part of the mocks, not super critical to keep (it probably shows up as a missing icon on windows if I had to guess, working on testing it now).

As for the schema, I was looking at it as a grouping like this in the file:

```
preInstall:
  ...
  
install:
  ...
  
postInstall:
  ...   
```

**Comment by jbeveland27** [comment]
I'm going to update the windows infra agent recipe to remove reference to the Logs being installed, as that should now come the `windows-logs.yml` when the guided install runs.

The icons don't show, but the loading spinner also doesn't show. Might be fine enough for now and we can address those issues post launch?

image

**Review by Julien4218 — DISMISSED** [review]

**Review by Julien4218 — APPROVED** [review]

**Pull request merged**
