### PR TITLE
Mysql improvements

### PR DESCRIPTION
**Pull request by carlossscastro**
Changes to The Mysql recipe:

* Allow the user retry inputting data
* Added connectivity test to mysql instance
* Improved user and permissions testing
* Decoupled infra agent presence testing from mysql tests to fail before user input

### CODE REVIEW

**Comment by carlossscastro** [comment]
@Julien4218 Thuis new PR already merges all tasks into a single task to avoid using tmp files to hold var values.

**Comment by Julien4218** [comment]
@carlossscastro the tests are currently timing out because they re waiting for an input to be entered. Similarly, we also want to support the non-interactive flow (assume yes).
Here is an example from the apm/.net linux recipe. https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/dotNet/debian-systemd.yml#L71-L90
We'll want to do something similar for all the inputs (the value can be injected through an env var).
Here is an example how the tests are writing the value in env vars (so the recipe can pick those up) https://github.com/newrelic/open-install-library/blob/main/test/deploy/linux/mysql/install/debian/roles/configure/tasks/main.yml#L55-L66

**Review by Julien4218 — APPROVED** [review]

**Comment by carlossscastro** [comment]
> @carlossscastro this looks very good to me.
> One caveats normally, if AssumeYes option is used, we should use the default value instead of prompting. I don't see this behavior happening anymore. The 2 questions for NR_CLI_DB_HOSTNAME and NR_CLI_DB_PORT should be defaulted when assume yes is specified.
> With that said, I think what you have is a good first step, and an amelioration of what we had before, so I'm happy to move this forward, and maybe keep in mind the defaulting in a subsequent iteration. I also think we shouldn't prompt for hostname and hard-wire to localhost since the assumption is that this should be local to the host anyway (we don't support distributed/remote install for now).

Hi @Julien4218 Thanks for you comments.

Regarding the points you mention:
1. HOSTNAME and PORT are set by using default values if the user just press enter on those inputs. you can see that here:
https://github.com/newrelic/open-install-library/pull/357/files#diff-69beb59d1ef06f584f89a6673b0a833bd3f1d38ec587d954cabe7bf74443acb1R92

and here:
https://github.com/newrelic/open-install-library/pull/357/files#diff-69beb59d1ef06f584f89a6673b0a833bd3f1d38ec587d954cabe7bf74443acb1R95

Those 2 lines will set the values as localhost and 3306 if the user just bypasses them pressing enter (assume default)

2. Regarding hardcoding hostname as localhost, it's true that we don't support remote install for now, however some users use the hostname to set their permissions and the integration credentials must match what they have set in their mysql environment.
Example: if I'm installing the integration on a host named `hostname1` and set my mysql permissions to allow user `newrelic` to login from `hostname1`, I specifically need to to setup the integration to connect to `hostname1`. If I try to connect using localhost, although they resolve to the same machine, mysql will only accept connection made to `hostname1`
It all depends on how the users and permissions are set on mysql.

We have seen this happening before where users had to change localhost by the "hostname" to have the integration working.

**Comment by Julien4218** [comment]
Got it, thanks for the details @carlossscastro 

Side note, AssumeYes means we should not prompt at all (when default exist). It's not as important in this recipe (because several questions dont have default and must be answered).

**Pull request merged**
