### PR TITLE
Replace yum update with makecache

### PR DESCRIPTION
**Pull request by Julien4218**

### CODE REVIEW

**Review by jbeveland27 — APPROVED** [review]

**Comment by jbeveland27** [comment]
@Julien4218 Seems like 3 of the debian recipes ([Couchbase](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/couchbase/debian.yml#L86), [RabbitMQ](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml#L99), [Varnish](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/varnish/debian.yml#L72)) might need a similar update?

```
sudo apt-get update -y
```

**Comment by jbeveland27** [comment]
And for completeness, maybe remove `-qq` from the [Nagios recipe](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/nagios/debian.yml#L71).

**Comment by Julien4218** [comment]
> @Julien4218 Seems like 3 of the debian recipes ([Couchbase](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/couchbase/debian.yml#L86), [RabbitMQ](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml#L99), [Varnish](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/varnish/debian.yml#L72)) might need a similar update?
> 
> ```
> sudo apt-get update -y
> ```

Actually I think Debian is different, apt-get update does not update all the packages, but only the repos. It is also what our doc recommend doing for install and update a OHI package. I think we're good with Debian

**Comment by jbeveland27** [comment]
> > @Julien4218 Seems like 3 of the debian recipes ([Couchbase](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/couchbase/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L86), [RabbitMQ](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L99), [Varnish](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/varnish/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L72)) might need a similar update?
> > ```
> > sudo apt-get update -y
> > ```
> 
> Actually I think Debian is different, apt-get update does not update all the packages, but only the repos. It is also what our doc recommend doing for install and update a OHI package. I think we're good with Debian

I mean the `-y` specifically is only in 3 of the debian OHIs currently

**Review by ctrombley — APPROVED** [review]

**Review by devfreddy — APPROVED** [review]

**Comment by Julien4218** [comment]
> > > @Julien4218 Seems like 3 of the debian recipes ([Couchbase](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/couchbase/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L86), [RabbitMQ](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L99), [Varnish](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/ohi/varnish/debian.yml?rgh-link-date=2021-03-11T23%3A19%3A47Z#L72)) might need a similar update?
> > > ```
> > > sudo apt-get update -y
> > > ```
> > 
> > 
> > Actually I think Debian is different, apt-get update does not update all the packages, but only the repos. It is also what our doc recommend doing for install and update a OHI package. I think we're good with Debian
> 
> I mean the `-y` specifically is only in 3 of the debian OHIs currently

I ll create a separate ticket to make all the Debian -y/-qq consistent, it's more than 3 that uses those variations

**Review by jbeveland27 — APPROVED** [review]

**Pull request merged**
